package com.yijiupi.kjjsp.pojo;

public class TalkPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.tid
     *
     * @mbggenerated
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.usname
     *
     * @mbggenerated
     */
    private String usname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.infor
     *
     * @mbggenerated
     */
    private String infor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.tid
     *
     * @return the value of talk.tid
     *
     * @mbggenerated
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.tid
     *
     * @param tid the value for talk.tid
     *
     * @mbggenerated
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.uid
     *
     * @return the value of talk.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.uid
     *
     * @param uid the value for talk.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.usname
     *
     * @return the value of talk.usname
     *
     * @mbggenerated
     */
    public String getUsname() {
        return usname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.usname
     *
     * @param usname the value for talk.usname
     *
     * @mbggenerated
     */
    public void setUsname(String usname) {
        this.usname = usname == null ? null : usname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.infor
     *
     * @return the value of talk.infor
     *
     * @mbggenerated
     */
    public String getInfor() {
        return infor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.infor
     *
     * @param infor the value for talk.infor
     *
     * @mbggenerated
     */
    public void setInfor(String infor) {
        this.infor = infor == null ? null : infor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk.time
     *
     * @return the value of talk.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk.time
     *
     * @param time the value for talk.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}