package com.yijiupi.kjjsp.pojo;

public class VisitorPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.uid
     *
     * @mbggenerated
     */
    private Integer uid;
    private String uname;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.fw_id
     *
     * @mbggenerated
     */
    private Integer fwId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.fw_name
     *
     * @mbggenerated
     */
    private String fwName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor.fw_time
     *
     * @mbggenerated
     */
    private String fwTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.id
     *
     * @return the value of visitor.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.id
     *
     * @param id the value for visitor.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.uid
     *
     * @return the value of visitor.uid
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.uid
     *
     * @param uid the value for visitor.uid
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.fw_id
     *
     * @return the value of visitor.fw_id
     * @mbggenerated
     */
    public Integer getFwId() {
        return fwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.fw_id
     *
     * @param fwId the value for visitor.fw_id
     * @mbggenerated
     */
    public void setFwId(Integer fwId) {
        this.fwId = fwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.fw_name
     *
     * @return the value of visitor.fw_name
     * @mbggenerated
     */
    public String getFwName() {
        return fwName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.fw_name
     *
     * @param fwName the value for visitor.fw_name
     * @mbggenerated
     */
    public void setFwName(String fwName) {
        this.fwName = fwName == null ? null : fwName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor.fw_time
     *
     * @return the value of visitor.fw_time
     * @mbggenerated
     */
    public String getFwTime() {
        return fwTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor.fw_time
     *
     * @param fwTime the value for visitor.fw_time
     * @mbggenerated
     */
    public void setFwTime(String fwTime) {
        this.fwTime = fwTime == null ? null : fwTime.trim();
    }

    public String getUname() {
        return uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }
}